##  Introduction to Numpy

In [1]:
import numpy as np

***Creating Arrays***
---
---

In [4]:
np.zeros(5) # Create array with zeros

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10) # Create array with ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(3, 10) # Create an array and fill the values with provided number

array([10, 10, 10])

In [10]:
np.array([1,2,3,4,5]) # Converting a python list into an array

array([1, 2, 3, 4, 5])

In [15]:
a = np.array([1,2,3,4,5])
a[3]

np.int64(4)

In [16]:
a[3] = 10 
a

array([ 1,  2,  3, 10,  5])

In [19]:
np.arange(3,10) # Creates an array from zero by default also between provided range

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(0,1, 11) #Creates an array with range and length provided

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

***Multidimensional Arrays***
---
------------------------------------------------------------

In [2]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
n = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
])

n[2][2]

np.int64(9)

In [8]:
n[2][2] = 20
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 20]])

In [10]:
n[2] = [1,1,1] # Changin values of rows
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [12]:
n[:,1] # Accesing column

array([2, 5, 1])

In [13]:
n[:,1] = [10,10,10] # Changing values of the column
n

array([[ 1, 10,  3],
       [ 4, 10,  6],
       [ 1, 10,  1]])

***Randomly Generated Array***
---
--------------------------------------------------------

In [18]:
np.random.seed(2) # This helps to regenerate the array with the same values every iteration
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [19]:
np.random.randn(5,2) # Creating array with normal distribution

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [20]:
np.random.seed(22)
np.random.randint(low = 0, high = 100, size = (5,2))  # Creates array with integers 

array([[ 4, 44],
       [64, 84],
       [ 8, 95],
       [93, 18],
       [14, 45]])

***Element Wise Operations***
---
---

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a + 1 

array([1, 2, 3, 4, 5])

In [24]:
a * 2

array([0, 2, 4, 6, 8])

In [26]:
b = (a*2) + 20
b

array([20, 22, 24, 26, 28])

In [27]:
a+b # Adding to arrays element wise addition

array([20, 23, 26, 29, 32])

***Comparison Operations***
---
---

In [28]:
a >= 2

array([False, False,  True,  True,  True])

In [29]:
b < 24

array([ True,  True, False, False, False])

In [31]:
a[a < b] #Returns the position of the elements in b for which the condition is true

array([0, 1, 2, 3, 4])

***Summarizing Operations***
---
---

In [33]:
a

array([0, 1, 2, 3, 4])

In [32]:
a.min()

np.int64(0)

In [35]:
b.max()

np.int64(28)

In [36]:
b.mean()

np.float64(24.0)

In [37]:
a.std()

np.float64(1.4142135623730951)