## Introduction to Linear Algebra

In [1]:
import numpy as np

***Multiplication***
---
---

***Vector Vector Multiplication***

In [ ]:
def vectior_vector_multiplication(v1, v2):
    
    # Vectors must be of the same length
    assert v1.shape == v2.shape
    
    n = v1.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + v1[i] * v2[i]
        
    return result

In [13]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6,])

u.shape[0], v.shape[0]

(3, 3)

In [14]:
vectior_vector_multiplication(u, v)

np.float64(32.0)

In [ ]:
# This numpy function does the same thing
np.dot(u, v)

np.int64(32)

***Matrix-Vectro Multiplication***

In [33]:
# Matrix Vecotor Multiplication
u = np.array([[2,4,5,6], 
              [1,2,1,2], 
              [3,1,2,1]])

v = np.array([4, 5, 6,])

u.shape, v.shape

((3, 4), (3,))

In [31]:
np.dot(u, v)

array([[34],
       [52],
       [70]])

***Matrix Matrix Multiplication***

In [ ]:
# Matrix-Matrix Multiplication
u = np.array([[2,4,5,6], a
              [1,2,1,2], 
              [3,1,2,1]])

v = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

u.shape, v.shape


((3, 4), (4, 3))

In [39]:
np.dot(u, v)

array([[113, 130, 147],
       [ 36,  42,  48],
       [ 31,  38,  45]])

***Identity Matrix***

In [41]:
i = np.eye(3)

In [42]:
np.dot(v, i)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

***Inverse of Matrix***

In [54]:
v = np.array([[1,2,3],
              [4,5,6],
              [7,8,10],
              [10,11,12]])

v[[0, 1, 2]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [55]:
vs = v[[0, 1, 2]]

vs_inv = np.linalg.inv(vs)

vs_inv

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [ ]:
np.dot(vs_inv,vs) # The values when rounded becomes zero and is regularly seen in identity matrix

array([[ 1.00000000e+00,  0.00000000e+00,  2.22044605e-16],
       [ 1.33226763e-15,  1.00000000e+00,  8.88178420e-16],
       [-7.77156117e-16,  0.00000000e+00,  1.00000000e+00]])